---
apiVersion: v1
kind: Pod
metadata:
  name: volume-test-migration
  namespace: default
spec:
  containers:
  - name: volume-test
    image: nginx:stable-alpine
    imagePullPolicy: IfNotPresent
    volumeMounts:
    - name: linear
      mountPath: /linear
    - name: mirror
      mountPath: /mirror
    - name: striped
      mountPath: /striped
    - name: default
      mountPath: /default
    - name: linear-old
      mountPath: /linear-old
    - name: mirror-old
      mountPath: /mirror-old
    - name: striped-old
      mountPath: /striped-old
    ports:
    - containerPort: 80
    resources:
      limits:
        cpu: 100m
        memory: 100M
  volumes:
  - name: linear
    persistentVolumeClaim:
      claimName: csi-driver-lvm-pvc-linear
  - name: mirror
    persistentVolumeClaim:
      claimName: csi-driver-lvm-pvc-mirror
  - name: striped
    persistentVolumeClaim:
      claimName: csi-driver-lvm-pvc-striped
  - name: default
    persistentVolumeClaim:
      claimName: csi-driver-lvm-pvc-default
  - name: linear-old
    persistentVolumeClaim:
      claimName: lvm-pvc-linear
  - name: mirror-old
    persistentVolumeClaim:
      claimName: lvm-pvc-mirror
  - name: striped-old
    persistentVolumeClaim:
      claimName: lvm-pvc-striped