---
apiVersion: core.gardener.cloud/v1beta1
kind: Shoot
metadata:
  name: local
  namespace: garden-local
  annotations:
    shoot.gardener.cloud/infrastructure-cleanup-wait-period-seconds: "0"
    shoot.gardener.cloud/cloud-config-execution-max-delay-seconds: "0"
spec:
  seedName: local
  cloudProfileName: local
  secretBindingName: local # dummy, doesn't contain any credentials
  region: local
  extensions:
  - type: csi-driver-lvm
    providerConfig:
      apiVersion: csi-driver-lvm.metal.extensions.gardener.cloud/v1alpha1
      kind: CsiDriverLvmConfig
      # Your configuration here
      # devicePattern: /dev/nvme[0-9]n[0-9]
      # hostWritePath: /etc/lib
  networking:
    type: calico
    nodes: 10.10.0.0/16
  provider:
    type: local
    workers:
    - name: local
      machine:
        type: local
      cri:
        name: containerd
      minimum: 1
      maximum: 1 # currently, only single-node clusters are supported
      maxSurge: 1
      maxUnavailable: 0
  kubernetes:
    kubelet:
      seccompDefault: true
      serializeImagePulls: false
      registryPullQPS: 10
      registryBurst: 20
      protectKernelDefaults: true
      streamingConnectionIdleTimeout: 5m
