---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: csi-driver-lvm-controller
  namespace: {{ .Release.Namespace }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: csi-driver-lvm-plugin
  namespace: {{ .Release.Namespace }}