---
{{- $storageClass := .Values.storageClasses.linear -}}
{{ if $storageClass.enabled }}
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name:  csi-driver-lvm-linear
{{- if not (empty $storageClass.additionalAnnotations) }}
  annotations:
    {{- $storageClass.additionalAnnotations | toYaml | nindent 4 -}}
{{ end }}
provisioner: lvm.csi.metal-stack.io
reclaimPolicy: {{ $storageClass.reclaimPolicy }}
volumeBindingMode: WaitForFirstConsumer
allowVolumeExpansion: true
parameters:
  type: "linear"
{{ end }}
---
{{- $storageClass := .Values.storageClasses.mirror -}}
{{ if $storageClass.enabled }}
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: csi-driver-lvm-mirror
{{- if not (empty $storageClass.additionalAnnotations) }}
  annotations:
    {{- $storageClass.additionalAnnotations | toYaml | nindent 4 -}}
{{ end }}
provisioner: lvm.csi.metal-stack.io
reclaimPolicy: {{ $storageClass.reclaimPolicy }}
volumeBindingMode: WaitForFirstConsumer
allowVolumeExpansion: true
parameters:
  type: "mirror"
{{ end }}
---
{{- $storageClass := .Values.storageClasses.striped -}}
{{ if $storageClass.enabled }}
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: csi-driver-lvm-striped
{{- if not (empty $storageClass.additionalAnnotations) }}
  annotations:
    {{- $storageClass.additionalAnnotations | toYaml | nindent 4 -}}
{{ end }}
provisioner: lvm.csi-metal-stack.io
reclaimPolicy: {{ $storageClass.reclaimPolicy }}
volumeBindingMode: WaitForFirstConsumer
allowVolumeExpansion: true
parameters:
  type: "striped"
{{ end }}
---
{{- $storageClass := .Values.storageClasses.linear -}}
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: csi-lvm
provisioner: lvm.csi.metal-stack.io
volumeBindingMode: WaitForFirstConsumer
reclaimPolicy: {{ $storageClass.reclaimPolicy }}
parameters:
  type: "linear"
---