//go:build !ignore_autogenerated
// +build !ignore_autogenerated

/*
2025 Copyright metal-stack Authors.
*/

// Code generated by deepcopy-gen. DO NOT EDIT.

package csidriverlvm

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CsiDriverLvmConfig) DeepCopyInto(out *CsiDriverLvmConfig) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	if in.DevicePattern != nil {
		in, out := &in.DevicePattern, &out.DevicePattern
		*out = new(string)
		**out = **in
	}
	if in.HostWritePath != nil {
		in, out := &in.HostWritePath, &out.HostWritePath
		*out = new(string)
		**out = **in
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CsiDriverLvmConfig.
func (in *CsiDriverLvmConfig) DeepCopy() *CsiDriverLvmConfig {
	if in == nil {
		return nil
	}
	out := new(CsiDriverLvmConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *CsiDriverLvmConfig) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}
